#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout

app_list_articles:
    path: /articles
    controller: App\Controller\articleController::listArticles
